version: "2"

run:
  timeout: 5m
  tests: true
  relative-path-mode: cfg

linters:
  default: standard
  enable:
    - asasalint
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilnil
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - unparam
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G104
  exclusions:
    rules:
      - path: '(.+)\.go$'
        text: "exported .* should have comment"
      - path: '(.+)\.go$'
        text: "should have a package comment"

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra:
        group-params: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
