services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GOCACHE: /go-cache
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/src/api
      - go_pkg:/go/pkg
      - go_cache:/go-cache

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 1s
      retries: 120
      start_period: 2s
    ports:
      - "5432:5432"

volumes:
  go_pkg:
  go_cache:
